swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "Easy Tests"
host: "api.easy-tests"
tags:
  - name: "users"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/users:
    get:
      summary: List all users
      operationId: listUsers
      tags:
        - users
      responses:
        "200":
          description: An array of users
          schema:
            $ref: '#/definitions/V1Users'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/V1Error'
  /v1/users/{userId}:
    get:
      summary: Info for a specific user
      operationId: showUserById
      tags:
        - users
      parameters:
        - name: userId
          in: path
          required: true
          description: The id of the user to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/V1User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/V1Error'
definitions:
  V1User:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  V1Users:
    type: array
    items:
      $ref: '#/definitions/V1User'
  V1Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
